[workspace]
resolver = "3"
members = [
    "crates/rouchdb-core",
    "crates/rouchdb-adapter-memory",
    "crates/rouchdb-changes",
    "crates/rouchdb-adapter-redb",
    "crates/rouchdb-adapter-http",
    "crates/rouchdb-replication",
]
