[package]
name = "rouchdb"
version = "0.1.0"
edition = "2024"
description = "Local-first document database with CouchDB replication protocol"

[dependencies]
rouchdb-core = { path = "../rouchdb-core" }
rouchdb-adapter-memory = { path = "../rouchdb-adapter-memory" }
rouchdb-adapter-redb = { path = "../rouchdb-adapter-redb" }
rouchdb-adapter-http = { path = "../rouchdb-adapter-http" }
rouchdb-changes = { path = "../rouchdb-changes" }
rouchdb-replication = { path = "../rouchdb-replication" }
rouchdb-query = { path = "../rouchdb-query" }
serde_json = "1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde_json = "1"
